apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: m1qj6o7va-python-gitops
  description: This is GitOps manifest for m1qj6o7va-python   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: tssc/gitops=m1qj6o7va-python
    backstage.io/kubernetes-id: m1qj6o7va-python 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: m1qj6o7va-python
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:m1qj6o7va-python
