apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: m1qj6o7va-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: m1qj6o7va-python 
  name: m1qj6o7va-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: m1qj6o7va-python 
